### PR TITLE
fix: import nuxt composables from #imports

### PR DESCRIPTION
**Pull request by danielroe**
## Changes

This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.

## Checklist
- [ ] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [ ] Accounted for the impact of any changes across different browsers

### CODE REVIEW

**Comment by danielroe** [comment]
Hm.

**Comment by GalacticHypernova** [comment]
I say reopen

**Comment by GalacticHypernova** [comment]
@pauldambra perhaps you can merge this? There's no reason not to, it's a DX improvement with no downsides.

**Comment by pauldambra** [comment]
Hey, 

Coincidentally, we've just set up a bot so we don't miss external contributions like this... sorry for the silence!

I've never used nuxt. I'll need to checkout the playground example before and after just for a check.

**Comment by pauldambra** [comment]
TestCafe is failing but that's ok since it's a fork and if this change can break the SDK (and I can't even imagine how it could) then I'd want to find out 🤣 

Sorry again for missing this! Thanks for taking the time to update it

**Comment by danielroe** [comment]
Not at all 😊

**Pull request merged**
