### PR TITLE
Add vite + remix app to playground to demo ES Module bug

### PR DESCRIPTION
**Pull request by matt-hernandez**
## Changes
This PR adds a Remix + Vite project to the app to demonstrate issue #908 . In order to reproduce that issue, you have to do `npm run build` and then `npm start`. This runs the app as if it's in a production environment. The app will crash and produce this output:

```
> start
> remix-serve ./build/server/index.js

file:///Users/matt.hernandez/Desktop/Projects/posthog-js/playground/remix-vite/build/server/index.js?t=1720462096078.148:7
import { PostHogProvider } from "posthog-js/react/dist/esm/index.js";
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'PostHogProvider' not found. The requested module 'posthog-js/react/dist/esm/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'posthog-js/react/dist/esm/index.js';
const { PostHogProvider } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:188:5)
    at DefaultModuleLoader.import (node:internal/modules/esm/loader:246:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:428:15)
    at run (/Users/matt.hernandez/Desktop/Projects/posthog-js/playground/remix-vite/node_modules/@remix-run/serve/dist/cli.js:112:15)
```

This bug is not reproducible when running `npm run dev`, which is the strangest behavior. It happens when running the app after build and during e2e tests that involve running a built version of the app in Playwright.
...

## Checklist
- [ *] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [ *] Accounted for the impact of any changes across different browsers
- [ *] Accounted for backwards compatibility of any changes (no breaking changes in posthog-js!)

### CODE REVIEW

**Comment by pauldambra** [comment]
amazing, thank you for spending time on this! 💖

**Comment by pauldambra** [comment]
sorry @matt-hernandez we had a replay incident this week that has absorbed a lot of my time... all sorted now
i'll pick this up as soon as i can!

**Comment by matt-hernandez** [comment]
@pauldambra I know the feeling too well 😆

**Comment by matt-hernandez** [comment]
Still watching this

**Comment by matt-hernandez** [comment]
Still watching this

**Comment by matt-hernandez** [comment]
Still watching this

**Comment by pauldambra** [comment]
hey @matt-hernandez i've been unexpectedly out of the office for three weeks so my to-do list is a little unhealthy right now 🙈 

haven't forgotten about this though

i don't know if @robbie-c has time to look at this before i do but i'll tag him in case i can nerd snipe him

https://xkcd.com/356/

**Comment by matt-hernandez** [comment]
We’ve seen a workaround for this that doesn’t seem unreasonable. I need to implement it to verify it on my end

**Comment by matt-hernandez** [comment]
Going to try the workaround today. If it works, I'll add it to this PR

**Comment by matt-hernandez** [comment]
@pauldambra I pushed up a workaround as the latest commit to this PR. I’ll try to give it a good test soon

**Comment by matt-hernandez** [comment]
@pauldambra I've set up a basic posthog event. If you make a `.env` file in the playground I've set up with a valid `PUBLIC_POSTHOG_KEY` value and a valid `PUBLIC_POSTHOG_HOST` (usually set to `https://app.posthog.com` for us), then this app should run and send events without fail.

I think this is a valid workaround. We managed to integrate this into our codebase and we're receiving our regular PostHog events without fail.

**Comment by matt-hernandez** [comment]
@pauldambra If you navigate to #908, there are two solutions posted by there by @ekojsalim and @zwhitchcox. Importing from `posthog-js/react` is the major problem with Vite. As soon as an import comes from that path, things go bad because Vite treats it like CommonJS instead of ESM. However, importing from `posthog-js` is fine. Vite, for some reason, has no problem with that. So the workaround solution from me and the other two people above involve us importing just from `posthog-js` and rolling our own `PostHogProvider`, like the one that would normally come from `posthog-js/react`.

**Pull request closed without merging**
