### PR TITLE
chore: Remove v2 rrweb checks

### PR DESCRIPTION
**Pull request by benjackwhite**
## Changes

Follow up after https://github.com/PostHog/posthog-js/pull/1078 is fully released

> WARNING: We should only merge this once the `recorder.js` is 100% rolled out to the CDN as rrweb2

* Removes all the extra loader code checking for the file to already have been loaded, instead just looking for the window rrweb method

## Checklist
- [ ] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [ ] Accounted for the impact of any changes across different browsers
- [ ] Accounted for backwards compatibility of any changes (no breaking changes in posthog-js!)

### CODE REVIEW

**Review by daibhin — APPROVED** [review]
Looks good whenever the other PR is merged and the CDN is ready. How long would you expect the cache to take?

**Comment by pauldambra** [comment]
> How long would you expect the cache to take?

It _should_ be a five minute cache. You can check the headers on the JS response. I guess maybe we'd need to check multiple URLs at the moment 🤷

**Review by daibhin — APPROVED** [review]

**Comment by daibhin** [comment]
Confirmed that https://internal-e.posthog.com/static/recorder.js now contains the v2 config:
```
...
{return{name:kn,observer:wn,options:e}};Jt&&(Jt.rrweb={record:At,version:"v2",rrwebVersion:"2.0.0-alpha.11"},Jt.rrwebConsoleRecord={getRecordConsolePlugin:function(e){return{name:"rrweb/console@1",observer:Ft,options:e}}},Jt.getRecordNetworkPlugin=Mn),e.NETWORK_PLUGIN_NAME=kn,e.default=At,e.findLast=ln,e.getRecordNetworkPlugin=Mn,e.patch=un,Object.defineProperty(e,"__esModule",{value:!0})}({});
//# sourceMappingURL=recorder.js.map
```

**Comment by daibhin** [comment]
Happy to merge this one now @benjackwhite?

**Pull request merged**
