### PR TITLE
fix: pass original fetch args along

### PR DESCRIPTION
**Pull request by pauldambra**
When wrapping fetch we take a url, init pair and create a request object

When we pass on and call the original fetch method we pass the request object. this is _technically_ equivalent to the original but not literally equivalent which can cause problems if there are further wrappers on fetch

see: https://github.com/PostHog/posthog-js/issues/1326

We actively don't want to alter the fetch details so it should be 100% safe to use the original args when calling the original fetch 🤷

### CODE REVIEW

**Review by daibhin — APPROVED** [review]
Change makes sense. I think we should be returning exactly the arguments we were given. Probably an oversight earlier on to have returned the constructed Request so worth fixing forward.

There's a risk we break this the other way e.g. customers have come to rely on the output of our fetch returning a `Request` object. We won't really know that without shipping.

My suggestion would be to get this out there as a minor bump. At least then people are more likely to be able to track the version bump if it does cause an issue for them. Secondly, there's always the escape hatch of staying on the previous version until they've had a chance to fix their reliant code (which should be trivial either way).

The only other alternative I can think of is passing `res = await originalFetch(req, init)` back but that feels less good. We'd be preserving current functionality at the expense of correctness. Given the points above it's probably just worth fixing everything now and dealing with any consequential issues that arise.

**Comment by weilandia** [comment]
Our site went down tonight because of an issue with Posthog overwriting fetch in this file. Not sure that this it eh culprit, but the changes made to window.fetch made RTKQuery unusable and left us with a very confusing FE bug that came down to the Posthog assets loading and breaking fetch.

**Comment by pauldambra** [comment]
oh yuck! so sorry @weilandia! will revert this change I've seen a few reports of similar and I'd be amazed if it was any of the other changes yesterday

**Comment by weilandia** [comment]
Thanks!

**Pull request merged**
