### PR TITLE
Improve feature flags

### LINKED ISSUE #57: Feature flag gives incorrect warning
If there are no feature flags matching my user, I get this warning when checking for any of them:

image

That's not true. The flags did load, there just wasn't anything there.

### LINKED ISSUE #70: Feature flag issue for SPA
### Bug description
For single-page apps(React in my case, but it seems it would affect anything that doesn't refresh after login) feature flags don't refresh upon logging in. 

We are using an 'anonymous' user with PostHog on our login page, and once logged in we update the user info with `posthog.identify` and `posthog.people.set`. We are also using `onFeatureFlags` to handle the feature flags. I don't think the react specifics some into play _too_ much, the main issue is that after identifying the user, by associating its email address and other information, the event callback isn't hit again with the updated feature flags.

### How to reproduce

1. Create a simple SPA with a button that sets the user via `posthog.identify` and `posthog.people.set`
2. Add an onFeatureFlag event handler
3. Push the button.

### Expected behavior
I would expect the feature flags of the newly identified user to trigger the handler.

### Environment

- PostHog cloud or self-managed? self-managed
- PostHog version/commit 1.10.1 `docker.io/posthog/posthog@sha256:2682fd9e5cb07f90c86de068ab45e1a0e8396ff8a81fac1c0dcd4fffafc0381c`
posthog-js 1.3.0

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Fixes #57
- Adds `.reloadFeatureFlags()` to `posthog`. Calling that updates all feature flags for the current user. (Fixes #70)
- Pass a callback to get the new flags after they reload: `.reloadFeatureFlags(flags => console.log(flags))`

No tests since there are no tests for feature flags... and I don't have time to add any now before the day is over :).

## Checklist
- [ ] Tests for new code (if applicable)
- [ ] TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)

### CODE REVIEW

**Comment by timgl** [comment]
Does it make sense to call this if identify is called? It feels like that should work automatically

**Comment by mariusandra** [comment]
We could call this directly, but we need to make sure identity is not only called, but the event is processed in the backend, giving the new feature flags. Alternatively, we could pass the new distinct_id somehow to /decide and use that to directly calculate the new flags.

**Comment by Ralph7C2** [comment]
Great! That would work if I could be sure that the call to get_distinct_id was updated, but it appears that is what you mean by "but we need to make sure identity is not only called, but the event is processed in the backend". 

Would it be possible to have the onFeatureFlags handler act as an event handler? It looks like we could get around the server part by using adding a call in the persistence module, like an observer pattern. I am likely missing a lot of the big picture, and haven't tested it, but something like:

```From 600aa7f58acf2bd15a992fb27f29ef4111173040 Mon Sep 17 00:00:00 2001
From: Ralph Landon <ralph7c2@gmail.com>
Date: Thu, 16 Jul 2020 09:41:38 -0700
Subject: [PATCH] Add event hander for feature flag updates

---
 src/posthog-core.js        |  3 ++-
 src/posthog-persistence.js | 17 ++++++++++++++++-
 2 files changed, 18 insertions(+), 2 deletions(-)

diff --git a/src/posthog-core.js b/src/posthog-core.js
index b6d8385..085ebb7 100644
--- a/src/posthog-core.js
+++ b/src/posthog-core.js
@@ -910,7 +910,8 @@ PostHogLib.prototype.isFeatureEnabled = function (key) {
  * @param {Function} [callback] The callback function will be called once the feature flags are ready. It'll return a list of feature flags enabled for the user.
  */
 PostHogLib.prototype.onFeatureFlags = function (callback) {
-    return this.feature_flags.onFeatureFlags(callback)
+    return this.persistence.addFeatureFlagsHandler(callback)
+    //return this.feature_flags.onFeatureFlags(callback)
 }
 
 /**
diff --git a/src/posthog-persistence.js b/src/posthog-persistence.js
index d87a328..5a5eebe 100644
--- a/src/posthog-persistence.js
+++ b/src/posthog-persistence.js
@@ -41,6 +41,8 @@ var PostHogPersistence = function (config) {
     this['props'] = {}
     this.campaign_params_saved = false
 
+    this['featureFlagEventHandlers'] = []
+
     if (config['persistence_name']) {
         this.name = 'ph_' + config['persistence_name']
     } else {
@@ -65,6 +67,17 @@ var PostHogPersistence = function (config) {
     this.save()
 }
 
+PostHogPersistence.prototype.addFeatureFlagsHandler = function(handler) {
+    this.featureFlagEventHandlers.push(handler)
+    return true
+}
+
+PostHogPersistence.prototype.onFeatureFlags = function(flags) {
+    this.featureFlagEventHandlers.forEach(handler => {
+        handler(flags)
+    });
+}
+
 PostHogPersistence.prototype.properties = function () {
     var p = {}
     // Filter out reserved properties
@@ -196,7 +209,9 @@ PostHogPersistence.prototype.register_once = function (props, default_value, day
 PostHogPersistence.prototype.register = function (props, days) {
     if (_.isObject(props)) {
         this.expire_days = typeof days === 'undefined' ? this.default_expiry : days
-
+        if (props?.$active_feature_flags) {
+            this.onFeatureFlags(props?.$active_feature_flags)
+        }
         _.extend(this['props'], props)
 
         this.save()
-- 
2.25.1

```

**Comment by Ralph7C2** [comment]
Passing in the distinct_id would also work for my use case I think, basically exposing 'decide' as 'featureFlagsForDistinctID(id): flags'

**Comment by mariusandra** [comment]
Hi @Ralph7C2! My apologies for the long wait before a reply (vacations period 😅)

I actually gave you some wrong information before. We *are* passing the `distinct_id` to the call to `/decide` (which responds with the feature flags), both when initializing the library and also [inside](https://github.com/PostHog/posthog-js/pull/71/files#diff-f01a3b74c9d30ab299f12d9e8546f897R40) `reloadFeatureFlags()`.

If your feature flags are only dependent on the user's ID (e.g. to calculate if the user is part of the flag's rollout), what is implemented in this PR should be enough. Just call `reloadFeatureFlags` after identify and you're all set. Please let me know if this is enough or not..

If the flag is also calculated from some `properties` you pass with `identify` (or `people.set`), we're back where we started from.... and must wait for the backend queue to finish processing the event before it has an effect on the flags. I'm really not sure how to get notified of this as it's all very async.

The idea to refactor `onFeatureFlags` into a more event handler type patter makes sense. I'll have a look at that shortly... and try to implement @timgl 's idea of reloading the flags directly after an identify call.

**Comment by Ralph7C2** [comment]
Yes, I believe as long as calling reloadFeatureFlags directly after identify gives the feature flags for the id passed in identify.

Our flow is:
- On navigation to landing page/sign-in/sign-up create a new random user(to start tracking immediately)
- On login, associate the random user with the logged in user's id

All feature flagging would be after logging in, and we would just need it to be consistent on the user id. My understanding of PostHog's feature flag code is it is some hashing function applied to the feature_flag_id+distinct_id, so as long as that distinct_id is the user_id we pass to identify, it'll work?

**Comment by mariusandra** [comment]
New changes: 
- `onFeatureFlags` is now an event handler. You give it callbacks and they get called when feature flags change.
- `reloadFeatureFlags` is now called on `identify` and triggers the callbacks that were sent to `onFeatureFlags`

Problems:
- there are zero tests for feature flags (https://github.com/PostHog/posthog-js/issues/50#issuecomment-654207934)
- capitalization is inconsistent with feature flag functions and all other ones (camelcase vs underscore) #60

@timgl ready to be reviewed

**Comment by mariusandra** [comment]
Merged with master and one change added:
- To avoid breaking existing behaviour, the `onFeatureFlags(callback)` function calls the callback immediately if the flags are loaded. Plus it gets called again when the flags change.

Ready for a look.

**Comment by timgl** [comment]
on it

**Comment by mariusandra** [comment]
@Ralph7C2 this is in `v1.4.1` ([changelog](https://github.com/PostHog/posthog-js/blob/master/CHANGELOG.md#141---2020-08-10)). Please report back if it works for you!

**Pull request merged**
