### PR TITLE
Bump version to 1.10.0

### PR DESCRIPTION
**Pull request by paolodamico**
## Changes

Bumps version to include latest advanced config. Matching docs, https://github.com/PostHog/posthog.com/pull/1206

## Checklist
- [ ] Tests for new code (if applicable)
- [ ] TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)

### CODE REVIEW

**Comment by paolodamico** [comment]
FYI publish to npm still pending, need permissions

**Comment by macobo** [comment]
Let's have team extensibility handle this

**Comment by mariusandra** [comment]
Thanks @paolodamico! The package is released! :)

I think we need to update the changelog manually this time though... So still one last pending todo...

**Comment by macobo** [comment]
Q: why are we releasing manually not using the bump labels?

**Comment by mariusandra** [comment]
Level 8 error this time.

**Pull request merged**
