### PR TITLE
feat(web-analytics): Add site_name in config and $site_name property

### PR DESCRIPTION
**Pull request by robbie-c**
## Changes
Add site_name to config, and $site_name property which is sent with this value. See https://github.com/PostHog/posthog/issues/18863 for context

## Checklist
- [x] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [x] Accounted for the impact of any changes across different browsers

### CODE REVIEW

**Review by benjackwhite — CHANGES_REQUESTED** [review]
Nothing wrong with the implementation but this feels like the wrong approach...

We already send a lot of data in default properties all of which we could derive the necessary info from server side instead. 

Why don't we just have a place in the UI where you can configure certain events to be attributed with certain sites? It's not far off from what we do with actions. 

The big pluses are:
1. You can configure it remotely (makes working with PostHog easy) 
2. It works retroactively, not just for events that later have that attribute added
3. We could in theory use it for more things - it can be "site" based for now but essentially you are sort of cohorting events which could be useful in a variety of quick filter ways

**Comment by mariusandra** [comment]
I never get tired of linking to this issue, which might be relevant: https://github.com/PostHog/posthog/issues/12181

**Comment by benjackwhite** [comment]
> > * You can configure it remotely (makes working with PostHog easy)
> > * It works retroactively, not just for events that later have that attribute added
> 
> Configuring remotely is nice, it does mean that it's probably more work to configure though.
> 
> Will think about this a bit

I could be wrong but I think the "more work" part would be on our side but for the user it would actually be "less work" in that they don't need any special client side config (and we don't need to add support for this to all of our SDKs), rather they "only" have to configure something in the app, which we could even auto configure like - "hey we see you have 4 domains, we have automatically created "sites" based on those domains".

Longer term this feels way more powerful than simply adding more and more data to the event payloads.

**Comment by robbie-c** [comment]
Closing this in favour of doing https://github.com/PostHog/posthog/issues/12181

**Pull request closed without merging**
