### PR TITLE
feat: Add captureStateless function

### PR DESCRIPTION
**Pull request by benjackwhite**
## Changes

Potential solution for second part of https://github.com/PostHog/posthog-js/issues/1172

## TODO
- [ ] Add test to check that capture stateless ignores optout

## Checklist
- [ ] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [ ] Accounted for the impact of any changes across different browsers
- [ ] Accounted for backwards compatibility of any changes (no breaking changes in posthog-js!)

### CODE REVIEW

**Comment by panrafal** [comment]
@benjackwhite looking at the current API surface it should do the job 👍  
I assume one will need to enable `send_instantly`, at least if user didn't opt-in (as in such case queue is not started).

**Comment by benjackwhite** [comment]
> @benjackwhite looking at the current API surface it should do the job 👍 I assume one will need to enable `send_instantly`, at least if user didn't opt-in (as in such case queue is not started).

Hmmm so the intention indeed, wasn't to bypass the opt out functionality... I think we could consider adding an option for that though

**Comment by panrafal** [comment]
> Hmmm so the intention indeed, wasn't to bypass the opt out functionality... I think we could consider adding an option for that though

My thinking here is, that people opt out of tracking - they don't want your analytics to be associated with them. The stateless capture enables you to do the same as you already can do on the backend anyway - to count the number of events happening, and my understanding is that it's perfectly fine under every privacy law. At least as long as don't track any user-specific data - probably as a user of this API I should remove the IP, user-agent string and screen dimensions as they can be used for fingerprinting.

**Comment by panrafal** [comment]
@benjackwhite any idea how long it can take for such change to be released (a very rough estimate)? I would love to decide if I should hold on and wait, or proceed with the current one and then refactor once it lands.

**Comment by benjackwhite** [comment]
> @benjackwhite any idea how long it can take for such change to be released (a very rough estimate)? I would love to decide if I should hold on and wait, or proceed with the current one and then refactor once it lands.

Can't really promise anything. Given other higher priority things I wouldn't put money on this being in in the next week...

**Comment by panrafal** [comment]
@benjackwhite Still I'm amazed you jumped so quickly into such a "fringe" idea! ❤️

**Comment by panrafal** [comment]
I'd love to keep it open and still very interested in this!

**Comment by panrafal** [comment]
Hey @benjackwhite any chance to reopen this?

**Comment by benjackwhite** [comment]
Re-opened. This was blocked by some issues with the gdpr-tooling which I fixed in another branch. Will try and have another look at it

**Comment by panrafal** [comment]
It's definitely still relevant :)

**Pull request closed without merging**
