### PR TITLE
fix: empty query param when calling external dependency toolbar.js

### PR DESCRIPTION
**Pull request by lucasra1**
## Changes

Changed the URL to use `t=<num>` as query param instead of empty/undefined param name (`v=161.1&=<num>`).

## Checklist
- [x] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [x] Accounted for the impact of any changes across different browsers
- [x] Accounted for backwards compatibility of any changes (no breaking changes in posthog-js!)

## Backstory

We use posthog in a nextjs application and use nextjs's rewrites as a proxy for better tracking. We noticed that the toolbar does not work on our site. when checking the logs we noticed that the rewrites did not work for the toolbar:

image

```
 code: 'ERR_INVALID_URL',
  input: 'https__ESC_COLON_//eu-assets.i.posthog.com/static/__ESC_COLON_path*'
```

But the `web-vitals.js` loaded without a problem...

image

Further investigation lead to the empty query param for the `toolbar.js` rotating token to bust  the cdn cache.

`?v=1.166.1?&=1728316200000`

The current stable version of next.js (`14.2.14`) has a "bug" that can't handle empty query params correctly in rewrites. The most recent canary version of nextjs seems to not have this bug anymore.

But still I think its better when posthog does not use an empty query param as this seems like something that was not intentional in the first place and secondly can result in unexpected behavior in frameworks like nextjs

### CODE REVIEW

**Comment by lucasra1** [comment]
Please keep open and review. Thanks

**Comment by lucasra1** [comment]
Please keep open and review. Thanks

**Review by pauldambra — APPROVED** [review]

**Comment by pauldambra** [comment]
fixes #1458

**Comment by lucasra1** [comment]
@pauldambra I think the github workflow needs to be approved. https://github.com/PostHog/posthog-js/actions/runs/11551538865

**Comment by pauldambra** [comment]
ugh... that should really work once merged 🤔

**Pull request merged**
