### PR TITLE
Fea/batch event posts

### PR DESCRIPTION
**Pull request by Tmunayyer**
**Description**
This PR adds support for batching event requests from the front end. The previous default behavior was to send a POST request on each event. With batching enabled a queue will be built of recorded events. Every 3 seconds a POST request will be sent with the queued events.

I noticed no batching was occurring from the frontend to the server. I thought it might be useful to have a system in place to group some of the default event captures together to reduce bandwidth usage and cpu usage on client and server.

**Ancillary**
1. A new configuration setting adding to turn on and off request batching at the top level.
`DEFAULT_CONFIG: { 'request_batching': true }`

2. The poll process will track empty poll counts. After 5 empty polls, it will pause itself, resuming on the next event capture.

3. If a custom callback or custom options are passed through for specific events, default non-batching behavior will persist. The reason for this is if someone using the library passes a callback and relies on the result, they don't want to wait for the next poll.

### CODE REVIEW

**Comment by timgl** [comment]
@Tmunayyer Thanks so much for this. This is great. A couple of thoughts:
- We have [a /batch api](https://github.com/PostHog/posthog/wiki/API) that we could use to only send 1 request rather than a couple. We would have to set the `timestamp` key, and that would involve doing [this issue](https://github.com/PostHog/posthog/issues/421).
- What happens when a user closes their browser before we've flushed the events? I think we might have to use something like [sendBeacon in the beforeunload event](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon)

**Comment by Tmunayyer** [comment]
I have a question concerning the first point:

I might be missing something here. Following the codebase, I identified that the endpoint the events are currently (one by one) being sent to on the Posthog Server is `/e`. At this endpoint, the `batch` property is checked and if its present, it performs the logic required to record the batch. This is the strategy I used for the implementation. Is this being refactored to use a `/batch` endpoint instead?

I'll dig into the send beacon stuff. Good catch, I noticed those workflows but it had slipped my mind!

**Comment by timgl** [comment]
Yeah in reality any of those endpoints do work. I'm struggling to find where you're setting the "batch" key though, but I'm sure I'm overlooking it?

**Comment by Tmunayyer** [comment]
Finally was able to wrap this up I think. 

1. I added timestamps in the capture function  as requested.
2. I don't think the send beacon functionality was working. There was no handler bound to the window `unload` event. I went ahead and added this into the _init function and it seems to be working now. There was also some special handling needed to set the content type since send beacon isn't the same api as a normal post request. I left a comment for some [official documentation that outlines the requirements](https://w3c.github.io/beacon/).

Something to note is that this event is fired on a page refresh. It could be a cool addition to PostHog to automatically reconcile leave and view events that happen within a certain amount of time by the same user to trigger a refresh event. 

A `$refresh` event might be insightful of something going wrong with the page that is not necessarily causing error to fire. Something like state getting into a position that the front end doesn't handle or render correctly and the user refreshes since something feels wrong etc.

Ex: 
   - `$pageleave` with timestamp `2020-04-04T22:38:46.991Z`
   - `$pageview` with timestamp `2020-04-04T22:38:47.221Z`

      Since these events are within 1 second of each other and if they have the same device_id or something then you could infer it was a refresh.

**Comment by timgl** [comment]
Great work on digging into this. I also love the `$pageleave` event, it's something I've been meaning to do and it means we'll be able to [do this ticket](https://github.com/PostHog/posthog/issues/334). I'll QA this tomorrow.

**Comment by timgl** [comment]
@Tmunayyer I just tested this. Maybe I'm missing something, but when I click a button multiple times quickly, it still does a request for each click. Do you know what might be going on here?

**Comment by Tmunayyer** [comment]
@timgl Yea thats my bad. When wrapping it up/testing things I left the setting 'request_batching' as false. I went ahead and switched it to true.

**Comment by timgl** [comment]
Moved to #10 for some small fixes

**Pull request closed without merging**
