### PR TITLE
Format code with prettier and lint with ESLint (#58 related)

### PR DESCRIPTION
**Pull request by Twixes**
Added code style configs and pre-commit hooks from the [main repo](https://github.com/posthog/PostHog), then formatted code. Is this OK to merge or might diffs be an issue?

### CODE REVIEW

**Comment by mariusandra** [comment]
That's great! Thank you @Twixes! :)

Just two things: 
- I realized I had a unpushed commit in master that just bumped the version in package.json. Could you merge that in?
- Can you ignore the ".html" files from being pretty? The "snippet.html" file contains some compressed and ugly code that should remain ugly. Probably safe to ignore the html files under "tests" as well.

**Comment by Twixes** [comment]
Sure, this should be fine now.

**Comment by mariusandra** [comment]
Great, thank you! Merged! :)

**Comment by mariusandra** [comment]
So I merged this, but upon closer look... after I run prettier myself on all the files, it appears that there are a bunch of standard-style function declarations in `master` that then get changed to the prettier style:

image

... but only in some files. Any idea how those ended up there? Feel free to submit a new PR that runs prettier again over them to unify the style.

**Comment by Twixes** [comment]
I think you have Prettier 1.x installed, while in `devDependencies` here it's Prettier 2.x. The main repo for instance is on 1.x.

**Comment by Twixes** [comment]
This is one of the differences between these 2 major versions, spaces before function parentheses.

**Comment by mariusandra** [comment]
Aha! That might be it! Great to hear the spaces thing made it to version 2 as well. I think it's a pretty practical rule.

We should probably upgrade prettier in the main repo then as well?

**Comment by Twixes** [comment]
Yeah, I think that'd be a good idea.

**Pull request merged**
