### PR TITLE
fix: Use rollup and fix define module issues

### PR DESCRIPTION
**Pull request by timgl**
## Changes

In progress. Only thing missing is minification of dist/array.js which I couldn't figure out with rollup
- Use rollup for array.js
- Set a specific module name for define to fix https://github.com/PostHog/posthog-js/issues/433

## Checklist
- [ ] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [ ] Accounted for the impact of any changes across different browsers

### CODE REVIEW

**Comment by mariusandra** [comment]
I fixed what was broken and changed the export type to `iife`, short for Immediately Invoked Function Execution. This made everything simpler. All the array code code is now executed in a enclosed function/scope, letting it handle injecting itself onto `window`, as it's doing anyway.

There's no possible conflict with a global `define` anymore, as everything is locally scoped.

We went down some bytes in size as well! 114k -> 79k, a 30% reduction!

```
# before
-rw-r--r--  1 marius  staff   114K Aug 16 10:55 array.js
-rw-r--r--  1 marius  staff   421K Aug 16 10:55 array.js.map

# after
-rw-r--r--  1 marius  staff    79K Aug 16 10:49 array.js
-rw-r--r--  1 marius  staff   409K Aug 16 10:49 array.js.map
```

**Review by benjackwhite — APPROVED** [review]
All looks sensible to me!

**Comment by timgl** [comment]
Nice! Do you feel confident releasing this as is, or should we do some testing somehow?

**Comment by mariusandra** [comment]
Just to be sure, I built, published and tested the new array.js locally on kea-docs, and everything worked. Events came in, sessions got recorded. The github test with IE11 even passes. Thus yep, let's release and get it on cloud for further testing.

**Review by mariusandra — APPROVED** [review]

**Pull request merged**
