### PR TITLE
Expose rrweb options to mask text in session recording

### PR DESCRIPTION
**Pull request by andrewcourtice**
## Changes
PostHog currently supports blocking elements in session recording by using the `ph-no-capture` CSS class. For most cases this is fine, however in some cases it makes more sense to mask the text (eg. `******`) instead of just rendering blank elements in the recording.

This is particularly useful for applications that display financial data. It can be helpful to see the magnitude of the figure but not the exact value of the figure.

This change simply forwards the rrweb text masking options through as an option for users and sets the default text masking class to `ph-mask`.

## Checklist
- [x] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [x] Accounted for the impact of any changes across different browsers

### CODE REVIEW

**Comment by andrewcourtice** [comment]
Hi PostHog Team - Just wondering why this one has had no feedback and been closed?

**Comment by neilkakkar** [comment]
Hey @andrewcourtice that's automated closing because of no activity. It flew under our radar - apologies! Have added the right person for a review :)

**Review by benjackwhite — APPROVED** [review]
Nice! Sorry this got ignored. Marked it for a minor bump once tests pass and it gets merged

**Comment by andrewcourtice** [comment]
@neilkakkar @benjackwhite No worries at all :) Thanks for looking into it. Loving PostHog by the way!

**Pull request merged**
