### PR TITLE
refactor: Rewrite PostHogSurveys class into function

### PR DESCRIPTION
**Pull request by fromaline**
## Changes
Rewrite PostHogSurveys class into function as proposed in issue #975
...

## Checklist
- [ x] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [ x] Accounted for the impact of any changes across different browsers

### CODE REVIEW

**Comment by pauldambra** [comment]
the bundled size action can't add a comment when run on forks

but is pretty cool, in that its output says what it would have commented 

----

**Size Change:** -824 B (0%) 

**Total Size:** 765 kB

| Filename | Size | Change |
| :--- | :---: | :---: |
| `dist/array.full.js` | 179 kB | -206 B (0%) |
| `dist/array.js` | 121 kB | -206 B (0%) |
| `dist/es.js` | 121 kB | -206 B (0%) |
| `dist/module.js` | 121 kB | -206 B (0%) |

<details><summary>ℹ️ <strong>View Unchanged</strong></summary>

| Filename | Size |
| :--- | :---: |
| `dist/exception-autocapture.js` | 12 kB |
| `dist/recorder-v2.js` | 104 kB |
| `dist/recorder.js` | 58.5 kB |
| `dist/surveys.js` | 48.7 kB |

</details>



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

----

so, this isn't a large enough change to make gains - or surveys isn't the place to target.

thanks for the PR, and you're welcome to keep trying, but I wouldn't say this falls into "good first issue" territory. It will probably take non-trivial changes - although I'd be happy to be proved wrong 😊

**Comment by fromaline** [comment]
Thanks for the feedback. I inspected the dist locally and it seems like your current setup doesn’t minify function names either. You can double-check it yourself, but it’s definitely the case on my end.

And I suspect, that’s exactly the reason why the sizes are identical in your bundled size action.

**Comment by pauldambra** [comment]
there's at least some minification going on e.g. scanning the generated code I see `var Vn=function(e,t,n)` but yep, there's definitely room for improvement here!

**Comment by fromaline** [comment]
Got it!
It’s not an insult in any way. I just tried to point out, that your original idea of rewriting classes into functions to decrease the bundle size, doesn’t work out of the box — `getSurveys` and `getMatchingSurveys` are still in the bundled code.

Btw, do you know are there any plans to decrease the bundle size of posthog in the near future? The tool is awesome and I’ll use it anyway, but the excessive size of JS library is a bit annoying. It even causes Lighthouse warnings, like good old google analytics #966

**Pull request closed without merging**
