### PR TITLE
Only hit onFeatureFlags callback after decide

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Right now we immediately return onFeatureFlags callbacks, even if flags haven't loaded.

@mariusandra given you changed this behaviour

## Checklist
- [ ] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [ ] Accounted for the impact of any changes across different browsers
- [ ] TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)

### CODE REVIEW

**Review by mariusandra — APPROVED** [review]
Looks good 👍

**Comment by wardloockx** [comment]
I'm experiencing the same issue. 

What would be a workaround for now? 

I get empty values in the `onFeatureFlags()` callback and want reliable values for multi-var flags. Calling `reloadFeatureFlags()` does not seem fire `onFeatureFlags` callback again.

**Comment by timgl** [comment]
What version of PostHog-js are you on? This pr should have fixed this

**Comment by mariusandra** [comment]
I think it was this fix: https://github.com/PostHog/posthog-js/pull/363

More [internal](https://posthog.slack.com/archives/C0113360FFV/p1643710956307509) [threads](https://posthog.slack.com/archives/C0113360FFV/p1643720956828379)

**Comment by pauldambra** [comment]
Hmmm, 

So, I read this PR as "don't immediately call a callback when it is registered if decide hasn't been hit" and #363 as "call the callbacks when decide is hit"

Between them they should "fix" the problem of decide possibly not having returned when onFeatureFlags is called

The important question being "What version of PostHog-js are you on?" for @wardloockx 

Since if they're on 1.17.7 it's not fixed :)

**Comment by wardloockx** [comment]
We are on 1.16.7. I will upgrade and see if that fixes it.

Thanks for the response.

**Comment by wardloockx** [comment]
I upgraded but in the same situation. I think this might be due to being on the free plan.

I see multivariant feature flags are premium now.

**Comment by pauldambra** [comment]
cc @rcmarron 

@wardloockx is this on a public URL we could look at?

**Pull request merged**
