### PR TITLE
chore: update default rrweb in array.full.js

### PR DESCRIPTION
**Pull request by daibhin**
## Changes

Default to using rrweb v2 in the `array.full.js`

Following up with a change to remove v1 entirely, but this we certainly want to do.

## Checklist
- [ ] Tests for new code (see [advice on the tests we use](https://github.com/PostHog/posthog-js#tiers-of-testing))
- [ ] Accounted for the impact of any changes across different browsers
- [ ] Accounted for backwards compatibility of any changes (no breaking changes in posthog-js!)

### CODE REVIEW

**Comment by marandaneto** [comment]
> +41.7 kB

@daibhin is the rrweb v2 smaller than v1?
if so, it might make sense to stack PRs on each other, otherwise, this version will increase by quite a bit already but not benefit the other gains.

**Comment by daibhin** [comment]
@marandaneto we'll find out in https://github.com/PostHog/posthog-js/pull/1078. My guess is that we should ship this regardless because including rrweb v1 in `array.full.js` is technically a bug because I'm not sure we even support it anymore

**Review by pauldambra — APPROVED** [review]
didn't run it locally... let's make sure we do before we ship it... (i think maybe cypress tests run session replay from array full)

I'd guess the bundle increase is that we'll only now be including network capture in the array full bundle

**Review by marandaneto — APPROVED** [review]

**Comment by daibhin** [comment]
Closing in favour of https://github.com/PostHog/posthog-js/pull/1078

**Pull request closed without merging**
