### PR TITLE
Add debug function

### PR DESCRIPTION
**Pull request by timgl**
## Changes

This adds a `posthog.debug()` function that will enable debugging info on any posthog.js instance. Call `posthog.debug(false)` to disable.

## Checklist
- [ ] Tests for new code (if applicable)
- [ ] TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)

### CODE REVIEW

**Comment by timgl** [comment]
had to add yarn.lock to get tests to pass

**Comment by mariusandra** [comment]
posthumous LGTM

**Comment by andrewm4894** [comment]
Would it be possible for me as a user to just define this as a cookie in my browser and then have it turned on? 

eg something like this? 

image

**Comment by timgl** [comment]
You can try running `localStorage.setItem('ph-debug', 'true')` in your dev console

**Pull request merged**
