### PR TITLE
LZ-String compression

### PR DESCRIPTION
**Pull request by mariusandra**
I implemented compression for the JS payloads. It's still sent as base64, just compressed with [lz-string](https://pieroxy.net/blog/pages/lz-string/index.html) before encoding.

Preliminary results are very promising! Here are the sizes of the base64 before and after compression:

image

These are events with batching enabled. The size difference is especially pronounced when I just clicked a lot on the same thing, generating multiple very similar events.

I'll post an issue soon for the python counterpart to this.

However... this is probably still a bit WIP since there's an open question: How should we solve the case that if you're using an older version of posthog, the newer snippet will stop working? Ideally we should do some "compression protocol negotiation", where the "/decide" endpoint also returns "ok to compress with lz-string".

### CODE REVIEW

**Comment by mariusandra** [comment]
Also, I inlined the lz-string JS. I'm a bit hesitant to include too many npm packages... especially of old and stale packages that might get replaced with pwned versions one day. Not saying it's going to happen here... but best to be careful. (I also had some trouble getting rollup to `build-module` with this npm package, so I just inlined it).

The only problem: it's not under a MIT/Apache license, but using [WTFPL](http://www.wtfpl.net/) instead. I think it's fine :D.

**Comment by timgl** [comment]
Another slightly annoying thing I just noticed while debugging something else: you can't copy the base64 and do `atob()` anymore to debug what's being sent. Maybe we should have an easy debug function for this?

**Comment by mariusandra** [comment]
Hey! Indeed this is still a WIP... just not yet in the status. It should definitely use the `supportedCompression` setting and there should also be tests here.

**Comment by mariusandra** [comment]
The compression part works now, but I broke something else... I think... 🤔 

The tests are now green, yet they are full of stuff like this:

image

I said it before, but this is a pretty horrible and untestable codebase. Functionality on the periphery (autocapture, gdpr, etc) is testable, but the core of the library uses horrible mutating globals to store its work... and I think it's easier to refactor the entire thing instead of getting it to cooperate with any testing framework.

**Comment by mariusandra** [comment]
This is _almost_ ready for a look! I couldn't figure out how to add proper tests that run through the logic of actually sending the events (in a reasonable timeframe). However testing locally, it seems to work:

image

I also fixed all the other flaky (mostly GDPR) tests in this PR.

....

There's just one issue that still pops up.

image

When I have the toolbar open (though not yet authorized), it keeps tracking $pageview events for me... and those are not compressed.

It's possible PR #63 somehow fixed this tracking, though I'm not sure... To Be Continued.

**Comment by mariusandra** [comment]
Regarding the `atob` question above. I have added a new method: `posthog.decodeLZ64(copy_the_string_here)` that will help with debugging:

image

**Comment by timgl** [comment]
Thanks for that debug function!

RE the $pageviews being captured, what are your thoughts there? On the one hand this _could_ be a very easy way to filter out a lot of traffic we don't need (e.g. ourselves), on the other hand it might be confusing for first time users or when you're trying to debug your own traffic

**Comment by mariusandra** [comment]
Regarding the issue I reported above:

> When I have the toolbar open (though not yet authorized), it keeps tracking $pageview events for me... and those are not compressed.

I found the issue. It's pretty simple. Since we take `editorParams` directly from `window.sessionStorage`, no request to `/decide` is made. Thus we don't have information about the supported compression methods... and therefore the payloads are not compressed. It's the same case for feature flags.

As proposed in #67, I think we shouldn't send any events in this case anyway... and thus it doesn't matter if compression is enabled or not. We could still make a request to `/decide` to get the feature flags, yet I think that's also outside of the scope of this PR.

Thus, @timgl , it's ready for a look if you agree with the above.

**Comment by mariusandra** [comment]
Hi @timgl this PR is ready for another look.

Changes: 
- adds `lz64` compression when `/decide` says so
- adds a basic test to check the `/decide` endpoint's compression param value is read
- fixes some other random gdpr tests
- removes one unused function `addOptOutCheckPostHogGroup`

**Comment by mariusandra** [comment]
Merged! `v1.3.3` released with this in.

**Pull request merged**
