### PR TITLE
auto update version

### PR DESCRIPTION
**Pull request by timgl**
## Changes

Copied from plugin-server. Auto update version on merge here and create a PR on /posthog

@Twixes Does this look correct? I literally just did `s/plugin-server/posthog-js`
## Checklist
- [ ] Tests for new code (if applicable)
- [ ] TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)

### CODE REVIEW

**Comment by macobo** [comment]
One difference we should figure out: Keeping a proper changelog.

**Comment by timgl** [comment]
Hm yeah. We could automate that as well just with the titles of the PR?

**Review by Twixes — COMMENTED** [review]
This should work 👍 now.
I added `bump major/minor/patch` labels with the autobump workflow too, very convenient in the plugin server repo. :)
But definitely need to include `CHANGELOG.md` support if we want to fully automate this. Would be simple if we only did squash merges here, which make for very convenient listing of all PRs merged since last release, not sure how to get that otherwise (without specifically hitting some GitHub API endpoints).

**Comment by timgl** [comment]
@Twixes have added squash merging only to this repo

**Pull request merged**
