### PR TITLE
Add TypeScript definitions (solves #23)

### PR DESCRIPTION
**Pull request by Twixes**
This PR adds TypeScript definitions for user-facing `posthog` methods.

Unfortunately these types only come "on top" of the existing codebase, so they may go out of sync if no care is taken. To decrease the risk of that happening, I suggest adding a pull request template with checklist:

- [ ] TypeScript definitions synced (if applicable)

Ideally the whole codebase could be refactored into TypeScript, which would also be good for code readability, maintainability, safety – generally beneficial – not necessarily feasible though.

Two exported module properties that aren't typed are `posthog.persistence` and `posthog.feature_flags`. They aren't mentioned in [the docs](https://posthog.com/docs/integrations/js-integration), so I wasn't sure if they actually are user-facing. If they should be, can be easily added too.

I think this addition has implications significant enough to warrant a minor version bump to 1.3.0.

### CODE REVIEW

**Comment by mariusandra** [comment]
Hey, very cool! 

Looking through the list of [files changed](https://github.com/PostHog/posthog-js/pull/61/files) I see a bunch of warnings about `any` types. 

image

I guess these are fine to ignore? If so, I'm happy to ignore them when merging!

Regarding the `persistence` and `feature_flags` exports. Yes, I think those should be exported as types as well. It is a bit annoying that `feature_flags` are in [snake_case](https://github.com/PostHog/posthog-js/issues/60), but what can we do... :/

In any case, I believe this library could/should be properly refactored and brought into the 2020s, including rewriting it in typescript... but obviously that's outside the scope of this issue :).

Regarding `1.3.0` - I agree, it should get a `minor` version bump. However I'd be happy if we can merge in a few other pending things (more tests) for that.

**Comment by mariusandra** [comment]
Regarding syncing the definitions, how should one do that?

**Comment by Twixes** [comment]
Added `persistence` and `feature_flags`. The `any`s in place are OK. Syncing – just updating signatures of exported methods after changing their code. As said, unfortunately this has to be done manually until the underlying code is rewritten in TS.

**Comment by mariusandra** [comment]
Thanks! Can you add also a PR template like you suggested? In addition to the checkbox the template should also explain for the first time contributor what this means. Something short like you said in your previous comment will be enough I think.

**Pull request merged**
