### PR TITLE
Device Type

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- Add the field `$device_type` (`Tablet`, `Mobile` or `Desktop`). 
- Should the third option be `Desktop`? I haven't used a "desktop computer" in years.
- Also adds a missing `react/yarn.lock`

## Checklist
- [ ] Tests for new code (if applicable)
- [ ] TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)

### CODE REVIEW

**Comment by mariusandra** [comment]
Not sure if this should be a `patch` or `minor` bump. I think the last `1.8.10` was big enough to have been `1.9.0`, and this could correct that... but 🤷

**Review by yakkomajuri — APPROVED** [review]
Great that you got this out quickly! 

A test would be nice but otherwise LGTM

**Comment by Twixes** [comment]
😳

**Comment by mariusandra** [comment]
I added a test to make sure the device matching itself works.

We didn't really test (e2e) that any browser property is added to a `posthog.capture` call. I added another test to check that `_.info.properties()` does return `$device_type`, which seems like the next best thing. Hope this covers enough cases to be approved.

**Pull request merged**
